max_width = 150
indent_style = "Visual"
match_arm_leading_pipes = "Always"
tab_spaces = 2
brace_style = "PreferSameLine"
color = "Always"
edition = "2021"
fn_single_line = true
imports_indent = "Visual"
imports_layout = "Vertical"
imports_granularity = "One"
merge_imports = true
normalize_comments = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
format_strings = true
spaces_around_ranges = true
struct_field_align_threshold = 36
version = "Two"
